[general]
bars = 16
framerate = 60
sleep_timer = 0

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 40
bar_delimiter = 59
frame_delimiter = 10

[smoothing]
noise_reduction = 25
